services:
  - type: web
    name: kyklos-backend
    env: node
    buildCommand: yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: kyklos-backend
          property: port

